services:
  - type: web
    name: really-cvserver
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python cvServerLite.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 