const data = {    
  "paracetamol": {
    "name": "Paracetamol",
    "purpose": "Fever reducer, pain reliever",
    "ingredients": "Paracetamol 500mg or 650mg",
    "sideEffects": "Rare: rash, liver toxicity in overdose",
    "warnings": "Avoid excess use, especially with liver conditions",
    "interactions": "Alcohol, anti-seizure drugs",
    "age": "Safe for children (dose-dependent)",
    "pregnancy": "Generally safe",
    "diabetes": "Safe",
    "trust": ["WHO-GMP", "Widely used globally"],
    "alternatives": ["Crocin 650", "Dolo 650", "Calpol"],
    "brands": ["Dolo", "Crocin", "Calpol"]
  },
  "cetirizine": {
    "name": "Cetirizine",
    "purpose": "Anti-allergy for cold, sneezing, hives",
    "ingredients": "Cetirizine 10mg",
    "sideEffects": "Drowsiness, dry mouth",
    "warnings": "Avoid driving, not for infants",
    "interactions": "Alcohol, sedatives",
    "age": "Not for children under 6",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["OTC antihistamine", "WHO-GMP"],
    "alternatives": ["Levocetirizine", "Loratadine"],
    "brands": ["Cetzine", "Zyrtec"]
  },
  "dolo_650": {
    "name": "Dolo 650",
    "purpose": "Fever and pain relief",
    "ingredients": "Paracetamol 650mg",
    "sideEffects": "Rare: liver strain in overdose",
    "warnings": "Avoid alcohol, liver disease caution",
    "interactions": "Alcohol, other paracetamol drugs",
    "age": "Safe above 12 years",
    "pregnancy": "Generally safe",
    "diabetes": "Safe",
    "trust": ["Doctor recommended", "GMP certified"],
    "alternatives": ["Calpol 650", "Crocin 650"],
    "brands": ["Dolo", "Micro Labs"]
  },
  "sinarest": {
    "name": "Sinarest",
    "purpose": "Cold, runny nose, headache relief",
    "ingredients": "Paracetamol, phenylephrine, chlorpheniramine",
    "sideEffects": "Drowsiness, dry mouth",
    "warnings": "Avoid alcohol, avoid in liver disease",
    "interactions": "Sedatives, MAOIs",
    "age": "Not below 6 years",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["OTC cold remedy"],
    "alternatives": ["Coldrin", "D-Cold"],
    "brands": ["Sinarest"]
  },
  "ors": {
    "name": "ORS (Oral Rehydration Salts)",
    "purpose": "Prevents dehydration due to diarrhea",
    "ingredients": "Glucose, sodium chloride, potassium chloride, citrate",
    "sideEffects": "None unless overused",
    "warnings": "Do not exceed recommended quantity",
    "interactions": "None",
    "age": "Safe for all ages",
    "pregnancy": "Safe",
    "diabetes": "Use sugar-free variant if diabetic",
    "trust": ["WHO-recommended", "FSSAI approved"],
    "alternatives": ["Electral", "Pedialyte"],
    "brands": ["Electral", "Dr. Morepen ORS"]
  },
  "electral": {
    "name": "Electral",
    "purpose": "Rehydration during diarrhea or heat stroke",
    "ingredients": "Dextrose, sodium chloride, potassium citrate",
    "sideEffects": "Bloating (rare)",
    "warnings": "Stick to dosage guidelines",
    "interactions": "None",
    "age": "Safe for all",
    "pregnancy": "Safe",
    "diabetes": "Check for low-sugar variant",
    "trust": ["Pharma-grade ORS", "WHO-formula"],
    "alternatives": ["ORS", "Rehydrate sachets"],
    "brands": ["Electral"]
  },
  "pantoprazole": {
    "name": "Pantoprazole",
    "purpose": "Reduces stomach acid, treats GERD",
    "ingredients": "Pantoprazole 40mg",
    "sideEffects": "Headache, nausea, flatulence",
    "warnings": "Avoid long-term use without doctor",
    "interactions": "Antiretrovirals, antifungals, iron",
    "age": "Safe above 12",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Rx/OTC acid reducer"],
    "alternatives": ["Omeprazole", "Esomeprazole"],
    "brands": ["Pantocid", "Pan 40"]
  },
  "omeprazole": {
    "name": "Omeprazole",
    "purpose": "Heartburn, acidity, ulcer protection",
    "ingredients": "Omeprazole 20mg",
    "sideEffects": "Bloating, constipation",
    "warnings": "Not for prolonged self-medication",
    "interactions": "Clopidogrel, antifungals",
    "age": "Safe for adults",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Common OTC acid reducer"],
    "alternatives": ["Pantoprazole", "Rantac"],
    "brands": ["Omez", "Ocid"]
  },
  "digene": {
    "name": "Digene",
    "purpose": "Antacid for acidity, gas, indigestion",
    "ingredients": "Magnesium hydroxide, aluminium hydroxide, simethicone",
    "sideEffects": "Constipation or loose stools",
    "warnings": "Avoid long-term use",
    "interactions": "Tetracycline, iron supplements",
    "age": "Safe for 12+",
    "pregnancy": "Consult doctor",
    "diabetes": "Check sugar-free version",
    "trust": ["OTC antacid", "Trusted by doctors"],
    "alternatives": ["Gelusil", "Eno"],
    "brands": ["Digene"]
  },
  "becosules": {
    "name": "Becosules",
    "purpose": "Vitamin B-complex supplement",
    "ingredients": "Vitamins B1, B2, B6, B12, C, folic acid",
    "sideEffects": "Rare: nausea, urine discoloration",
    "warnings": "Do not exceed dosage",
    "interactions": "Minimal",
    "age": "Safe for adults",
    "pregnancy": "Safe with doctor's advice",
    "diabetes": "Safe",
    "trust": ["OTC multivitamin"],
    "alternatives": ["Zincovit", "Revital H"],
    "brands": ["Becosules"]
  },
  "calpol": {
    "name": "Calpol",
    "purpose": "Fever and mild pain relief",
    "ingredients": "Paracetamol 250mg/5ml (syrup), 500mg or 650mg (tablet)",
    "sideEffects": "Rare: rash, liver toxicity in overdose",
    "warnings": "Avoid overdose, especially in children",
    "interactions": "Alcohol, other hepatotoxic drugs",
    "age": "Safe for all (dose-specific)",
    "pregnancy": "Generally safe",
    "diabetes": "Safe",
    "trust": ["Pediatrician-trusted"],
    "alternatives": ["Dolo", "Crocin"],
    "brands": ["Calpol"]
  },
  "crocin": {
    "name": "Crocin",
    "purpose": "Fever and mild pain",
    "ingredients": "Paracetamol 500mg or 650mg",
    "sideEffects": "Liver issues in overdose",
    "warnings": "Avoid double-dosing with other paracetamol meds",
    "interactions": "Alcohol",
    "age": "Children's syrup and tablets available",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Trusted Indian brand"],
    "alternatives": ["Dolo", "Calpol"],
    "brands": ["Crocin"]
  },
  "zincovit": {
    "name": "Zincovit",
    "purpose": "Multivitamin and antioxidant support",
    "ingredients": "Zinc, Vitamin C, B-complex, selenium",
    "sideEffects": "Mild nausea, metallic taste",
    "warnings": "Do not exceed dosage",
    "interactions": "Minimal with other vitamins",
    "age": "Safe above 12",
    "pregnancy": "Consult doctor",
    "diabetes": "Check sugar-free version",
    "trust": ["Pharma-grade supplement"],
    "alternatives": ["Becosules", "Revital H"],
    "brands": ["Zincovit"]
  },
  "d_cold_total": {
    "name": "D-Cold Total",
    "purpose": "Fever, nasal congestion, allergy relief",
    "ingredients": "Paracetamol, phenylephrine, chlorpheniramine",
    "sideEffects": "Drowsiness, dizziness",
    "warnings": "Avoid driving and alcohol",
    "interactions": "Sedatives, antihistamines",
    "age": "Not for children under 12",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["OTC combo for cold"],
    "alternatives": ["Sinarest", "Coldrin"],
    "brands": ["D-Cold"]
  },
  "coldrin": {
    "name": "Coldrin",
    "purpose": "Cold, headache, fever relief",
    "ingredients": "Paracetamol, phenylephrine, caffeine",
    "sideEffects": "Increased BP, drowsiness",
    "warnings": "Avoid in high blood pressure",
    "interactions": "Alcohol, MAOIs",
    "age": "Not for children under 12",
    "pregnancy": "Consult doctor",
    "diabetes": "Caution advised",
    "trust": ["OTC cold medicine"],
    "alternatives": ["Sinarest", "D-Cold"],
    "brands": ["Coldrin"]
  },
  "disprin": {
    "name": "Disprin",
    "purpose": "Headache, mild pain, fever",
    "ingredients": "Aspirin 325mg",
    "sideEffects": "Acidity, gastric irritation, bleeding risk",
    "warnings": "Avoid in ulcers, asthma, bleeding disorders",
    "interactions": "Anticoagulants, alcohol",
    "age": "Not for children under 16",
    "pregnancy": "Avoid (especially in 3rd trimester)",
    "diabetes": "Safe with caution",
    "trust": ["Legacy pain reliever"],
    "alternatives": ["Paracetamol", "Ibuprofen"],
    "brands": ["Disprin"]
  },
  "isabgol": {
    "name": "Isabgol",
    "purpose": "Relieves constipation, promotes bowel regularity",
    "ingredients": "Psyllium husk",
    "sideEffects": "Bloating, flatulence (initially)",
    "warnings": "Take with plenty of water",
    "interactions": "Can affect absorption of some meds",
    "age": "Safe above 6 years",
    "pregnancy": "Safe",
    "diabetes": "Safe (sugar-free variants available)",
    "trust": ["FSSAI", "Ayurvedic laxative"],
    "alternatives": ["Cremaffin", "Looz"],
    "brands": ["Sat Isabgol", "Patanjali Isabgol"]
  },
  "looz": {
    "name": "Looz Syrup",
    "purpose": "Constipation relief",
    "ingredients": "Lactulose 10g/15ml",
    "sideEffects": "Bloating, gas, diarrhea in excess",
    "warnings": "Avoid in galactose intolerance",
    "interactions": "Avoid antacids close to dose",
    "age": "Safe for all age groups (doctor-guided)",
    "pregnancy": "Safe",
    "diabetes": "Use sugar-free if needed",
    "trust": ["Doctor-recommended laxative"],
    "alternatives": ["Duphalac", "Isabgol"],
    "brands": ["Looz"]
  },
  "cremaffin": {
    "name": "Cremaffin",
    "purpose": "Constipation relief syrup",
    "ingredients": "Liquid paraffin, milk of magnesia",
    "sideEffects": "Loose motions, cramping",
    "warnings": "Not for long-term use",
    "interactions": "May reduce absorption of other drugs",
    "age": "Safe for short-term use (12+ years)",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Popular OTC laxative"],
    "alternatives": ["Looz", "Isabgol"],
    "brands": ["Cremaffin"]
  },
  "benadryl": {
    "name": "Benadryl",
    "purpose": "Cough suppressant and allergy relief",
    "ingredients": "Diphenhydramine, ammonium chloride, sodium citrate",
    "sideEffects": "Drowsiness, dry mouth",
    "warnings": "Avoid driving, alcohol; not for asthma-related cough",
    "interactions": "Sedatives, alcohol",
    "age": "Above 6 years (children's syrup available)",
    "pregnancy": "Consult doctor",
    "diabetes": "Check sugar-free variant",
    "trust": ["Popular OTC cough syrup"],
    "alternatives": ["Corex-D", "Zedex"],
    "brands": ["Benadryl"]
  },
  "zedex": {
    "name": "Zedex",
    "purpose": "Dry cough relief",
    "ingredients": "Dextromethorphan, chlorpheniramine, phenylephrine",
    "sideEffects": "Drowsiness, mild dizziness",
    "warnings": "Not for wet/productive cough",
    "interactions": "MAO inhibitors, alcohol",
    "age": "Above 6 years",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Doctor-trusted syrup"],
    "alternatives": ["Benadryl", "Corex D"],
    "brands": ["Zedex"]
  },
  "corex_d": {
    "name": "Corex D",
    "purpose": "Dry cough relief",
    "ingredients": "Dextromethorphan, chlorpheniramine",
    "sideEffects": "Drowsiness, nausea",
    "warnings": "Do not exceed dose; avoid alcohol",
    "interactions": "CNS depressants",
    "age": "Above 6 years",
    "pregnancy": "Consult doctor",
    "diabetes": "Check label for sugar",
    "trust": ["Marketed by Pfizer"],
    "alternatives": ["Zedex", "Ascoril D"],
    "brands": ["Corex"]
  },
  "ascoril_ls": {
    "name": "Ascoril LS",
    "purpose": "Wet cough relief",
    "ingredients": "Levosalbutamol, ambroxol, guaiphenesin",
    "sideEffects": "Tremors, nausea, restlessness",
    "warnings": "Use under supervision in heart patients",
    "interactions": "Beta-blockers",
    "age": "Above 6 years",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Prescribed OTC mucolytic"],
    "alternatives": ["Ambrodil-L", "BroZedex LS"],
    "brands": ["Ascoril"]
  },
  "ambrodil_ls": {
    "name": "Ambrodil LS",
    "purpose": "Loosens mucus in chest congestion",
    "ingredients": "Levosalbutamol, ambroxol, guaiphenesin",
    "sideEffects": "Headache, mild gastric discomfort",
    "warnings": "Use caution in asthma",
    "interactions": "Theophylline, beta-blockers",
    "age": "Above 6 years",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Effective mucolytic"],
    "alternatives": ["Ascoril LS", "Zedex LS"],
    "brands": ["Ambrodil"]
  },
  "avomine": {
    "name": "Avomine",
    "purpose": "Motion sickness and nausea relief",
    "ingredients": "Promethazine hydrochloride",
    "sideEffects": "Drowsiness, dizziness",
    "warnings": "Avoid alcohol and machinery",
    "interactions": "CNS depressants",
    "age": "Above 5 years",
    "pregnancy": "Avoid unless advised",
    "diabetes": "Safe",
    "trust": ["Used widely in travel medicine"],
    "alternatives": ["Domstal", "Emeset"],
    "brands": ["Avomine"]
  },
  "domstal": {
    "name": "Domstal",
    "purpose": "Nausea, bloating, and gastric motility",
    "ingredients": "Domperidone 10mg",
    "sideEffects": "Dry mouth, abdominal cramps",
    "warnings": "Avoid in heart conditions",
    "interactions": "Erythromycin, antifungals",
    "age": "Safe above 12",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["GI motility regulator"],
    "alternatives": ["Emeset", "Ondem"],
    "brands": ["Domstal"]
  },
  "emeset": {
    "name": "Emeset",
    "purpose": "Vomiting and nausea control",
    "ingredients": "Ondansetron 4mg",
    "sideEffects": "Constipation, headache",
    "warnings": "Do not exceed dose",
    "interactions": "Apomorphine",
    "age": "Safe above 4 years",
    "pregnancy": "Generally safe",
    "diabetes": "Safe",
    "trust": ["WHO essential drug"],
    "alternatives": ["Domstal", "Ondem"],
    "brands": ["Emeset"]
  },
  "ondem": {
    "name": "Ondem",
    "purpose": "Nausea, vomiting, travel sickness",
    "ingredients": "Ondansetron 4mg or 8mg",
    "sideEffects": "Constipation, dizziness",
    "warnings": "Avoid alcohol",
    "interactions": "SSRIs, apomorphine",
    "age": "Safe above 4 years",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["WHO-listed antiemetic"],
    "alternatives": ["Emeset", "Domstal"],
    "brands": ["Ondem"]
  },
  "enzoflam": {
    "name": "Enzoflam",
    "purpose": "Pain, inflammation, swelling",
    "ingredients": "Diclofenac, paracetamol, serratiopeptidase",
    "sideEffects": "Stomach upset, heartburn",
    "warnings": "Avoid in ulcers, kidney disease",
    "interactions": "Aspirin, warfarin",
    "age": "Adults only",
    "pregnancy": "Avoid in pregnancy",
    "diabetes": "Safe with food",
    "trust": ["Effective anti-inflammatory"],
    "alternatives": ["Zerodol P", "Voveran"],
    "brands": ["Enzoflam"]
  },
  "voveran": {
    "name": "Voveran",
    "purpose": "Pain relief and anti-inflammatory",
    "ingredients": "Diclofenac sodium 50mg",
    "sideEffects": "Gastric irritation, nausea",
    "warnings": "Avoid in ulcers, kidney/liver issues",
    "interactions": "NSAIDs, anticoagulants",
    "age": "Above 18 years",
    "pregnancy": "Avoid during pregnancy",
    "diabetes": "Safe with caution",
    "trust": ["Doctor-prescribed analgesic"],
    "alternatives": ["Enzoflam", "Zerodol P"],
    "brands": ["Voveran", "Voltaren"]
  },
  "zerodol_p": {
    "name": "Zerodol P",
    "purpose": "Pain, swelling, and fever",
    "ingredients": "Aceclofenac 100mg + Paracetamol 325mg",
    "sideEffects": "Stomach upset, dizziness",
    "warnings": "Avoid long-term use",
    "interactions": "NSAIDs, diuretics",
    "age": "Adults only",
    "pregnancy": "Avoid unless advised",
    "diabetes": "Safe",
    "trust": ["Common pain combo"],
    "alternatives": ["Enzoflam", "Voveran"],
    "brands": ["Zerodol"]
  },
  "ibuprofen": {
    "name": "Ibuprofen",
    "purpose": "Fever, headache, body pain",
    "ingredients": "Ibuprofen 400mg",
    "sideEffects": "Acidity, dizziness",
    "warnings": "Avoid in ulcers, kidney disease",
    "interactions": "NSAIDs, alcohol",
    "age": "Above 12 years",
    "pregnancy": "Avoid in 3rd trimester",
    "diabetes": "Safe with food",
    "trust": ["WHO essential medicine"],
    "alternatives": ["Paracetamol", "Diclofenac"],
    "brands": ["Brufen", "Ibugesic"]
  },
  "brufen": {
    "name": "Brufen",
    "purpose": "Pain, inflammation, fever",
    "ingredients": "Ibuprofen 400mg",
    "sideEffects": "Stomach upset, nausea",
    "warnings": "Avoid if history of ulcers or GI bleeding",
    "interactions": "Aspirin, diuretics",
    "age": "Above 12 years",
    "pregnancy": "Avoid in late pregnancy",
    "diabetes": "Safe with caution",
    "trust": ["Widely used painkiller"],
    "alternatives": ["Ibugesic", "Paracetamol"],
    "brands": ["Brufen"]
  },
  "ibugesic": {
    "name": "Ibugesic",
    "purpose": "Pain and fever relief",
    "ingredients": "Ibuprofen 200mg/400mg",
    "sideEffects": "Acidity, rash",
    "warnings": "Avoid overuse; take with food",
    "interactions": "Blood thinners, NSAIDs",
    "age": "Safe for 6+ in syrup form",
    "pregnancy": "Avoid in 3rd trimester",
    "diabetes": "Safe",
    "trust": ["Pediatric syrup available"],
    "alternatives": ["Brufen", "Paracetamol"],
    "brands": ["Ibugesic"]
  },
  "cyclopam": {
    "name": "Cyclopam",
    "purpose": "Stomach cramps, menstrual pain",
    "ingredients": "Dicyclomine + Paracetamol",
    "sideEffects": "Dry mouth, dizziness",
    "warnings": "Avoid in glaucoma, GI obstruction",
    "interactions": "Anticholinergics",
    "age": "Adults only",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Antispasmodic + analgesic"],
    "alternatives": ["Meftal Spas"],
    "brands": ["Cyclopam"]
  },
  "meftal_spas": {
    "name": "Meftal Spas",
    "purpose": "Menstrual pain, stomach cramps",
    "ingredients": "Mefenamic acid + Dicyclomine",
    "sideEffects": "Nausea, dizziness",
    "warnings": "Avoid in ulcers, kidney issues",
    "interactions": "NSAIDs, antacids",
    "age": "Adults only",
    "pregnancy": "Avoid unless prescribed",
    "diabetes": "Safe",
    "trust": ["Common painkiller for periods"],
    "alternatives": ["Cyclopam", "Spasmoproxyvon"],
    "brands": ["Meftal"]
  },
  "rantac": {
    "name": "Rantac",
    "purpose": "Acidity, indigestion, ulcers",
    "ingredients": "Ranitidine 150mg",
    "sideEffects": "Headache, constipation",
    "warnings": "Avoid long-term use",
    "interactions": "Ketoconazole, iron salts",
    "age": "Above 12 years",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Old-generation antacid"],
    "alternatives": ["Pantoprazole", "Omeprazole"],
    "brands": ["Rantac"]
  },
  "ranitidine": {
    "name": "Ranitidine",
    "purpose": "Acidity and gastric ulcers",
    "ingredients": "Ranitidine 150mg",
    "sideEffects": "Constipation, headache",
    "warnings": "Withdrawn in some markets — use caution",
    "interactions": "Antifungals, iron",
    "age": "Adults only",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Still used in India OTC"],
    "alternatives": ["Rantac", "Pantoprazole"],
    "brands": ["Rantac", "Zinetac"]
  },
  "zinetac": {
    "name": "Zinetac",
    "purpose": "Acidity and indigestion",
    "ingredients": "Ranitidine 150mg",
    "sideEffects": "Flatulence, dizziness",
    "warnings": "Avoid if allergic to ranitidine",
    "interactions": "Antifungals, iron",
    "age": "Adults only",
    "pregnancy": "Generally safe",
    "diabetes": "Safe",
    "trust": ["OTC acid reducer"],
    "alternatives": ["Rantac", "Pantocid"],
    "brands": ["Zinetac"]
  },
  "calcium_sandoz": {
    "name": "Calcium Sandoz",
    "purpose": "Calcium supplement for bone health",
    "ingredients": "Calcium lactate gluconate + Calcium carbonate",
    "sideEffects": "Constipation, bloating",
    "warnings": "Avoid in kidney stones or high calcium levels",
    "interactions": "Iron, tetracyclines, thyroid meds",
    "age": "Safe for all ages (form-specific)",
    "pregnancy": "Safe",
    "diabetes": "Safe (check sugar-free variant)",
    "trust": ["Doctor-recommended supplement"],
    "alternatives": ["Shelcal", "Calcimax"],
    "brands": ["Calcium Sandoz"]
  },
  "shelcal": {
    "name": "Shelcal",
    "purpose": "Calcium and Vitamin D3 supplement",
    "ingredients": "Calcium carbonate + Vitamin D3",
    "sideEffects": "Mild GI upset, flatulence",
    "warnings": "Avoid overdose, especially with kidney issues",
    "interactions": "Iron, magnesium, antibiotics",
    "age": "Adults only",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Trusted calcium source"],
    "alternatives": ["Calcium Sandoz", "Calcimax"],
    "brands": ["Shelcal"]
  },
  "calcimax": {
    "name": "Calcimax",
    "purpose": "Bone health, calcium and mineral support",
    "ingredients": "Calcium carbonate, magnesium, zinc, Vitamin D3",
    "sideEffects": "Bloating, nausea (rare)",
    "warnings": "Avoid excessive intake",
    "interactions": "Iron, thyroid hormone",
    "age": "Adults",
    "pregnancy": "Safe under advice",
    "diabetes": "Safe",
    "trust": ["Balanced calcium supplement"],
    "alternatives": ["Shelcal", "Calcium Sandoz"],
    "brands": ["Calcimax"]
  },
  "neurobion": {
    "name": "Neurobion Forte",
    "purpose": "B-complex vitamin supplement",
    "ingredients": "B1, B2, B3, B6, B12, folic acid",
    "sideEffects": "Urine color change, mild nausea",
    "warnings": "Not a substitute for a full diet",
    "interactions": "Minimal",
    "age": "Safe for adults",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Doctor-trusted B-vitamin brand"],
    "alternatives": ["Becosules", "Zincovit"],
    "brands": ["Neurobion"]
  },
  "vitamin_c_limcee": {
    "name": "Limcee",
    "purpose": "Vitamin C supplement, immunity support",
    "ingredients": "Vitamin C (Ascorbic Acid)",
    "sideEffects": "Stomach upset in high dose",
    "warnings": "Excess may cause kidney stones",
    "interactions": "Aluminum antacids, estrogens",
    "age": "Safe above 6 years",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Widely used Vitamin C"],
    "alternatives": ["Celin", "Ceeplus"],
    "brands": ["Limcee"]
  },
  "celin": {
    "name": "Celin",
    "purpose": "Vitamin C supplement",
    "ingredients": "Ascorbic Acid 500mg",
    "sideEffects": "Nausea, acidity (if taken on empty stomach)",
    "warnings": "Avoid mega-dosing",
    "interactions": "Iron absorption enhancer",
    "age": "Safe above 6 years",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Classic Indian Vitamin C"],
    "alternatives": ["Limcee", "Ceeplus"],
    "brands": ["Celin"]
  },
  "ceeplus": {
    "name": "Ceeplus",
    "purpose": "Immunity and antioxidant support",
    "ingredients": "Vitamin C + Zinc",
    "sideEffects": "Bloating, GI upset (rare)",
    "warnings": "Avoid taking on empty stomach",
    "interactions": "Enhances iron absorption",
    "age": "Safe for all ages (dose-specific)",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Dual-action vitamin"],
    "alternatives": ["Limcee", "Celin"],
    "brands": ["Ceeplus"]
  },
  "feronia_xs": {
    "name": "Feronia-XT",
    "purpose": "Iron supplement for anemia",
    "ingredients": "Ferrous ascorbate + folic acid + zinc",
    "sideEffects": "Black stools, constipation",
    "warnings": "Avoid in hemochromatosis",
    "interactions": "Calcium, antacids",
    "age": "Safe for teens and adults",
    "pregnancy": "Safe and recommended",
    "diabetes": "Safe",
    "trust": ["Gynecologist-recommended"],
    "alternatives": ["Dexorange", "Livogen"],
    "brands": ["Feronia"]
  },
  "dexorange": {
    "name": "Dexorange",
    "purpose": "Iron and folic acid supplement",
    "ingredients": "Iron, Vitamin B12, folic acid",
    "sideEffects": "Stomach upset, black stool",
    "warnings": "Avoid overuse",
    "interactions": "Calcium, antacids",
    "age": "Teens and adults",
    "pregnancy": "Recommended",
    "diabetes": "Check sugar content",
    "trust": ["Classic Indian iron tonic"],
    "alternatives": ["Feronia-XT", "Livogen"],
    "brands": ["Dexorange"]
  },
  "livogen": {
    "name": "Livogen",
    "purpose": "Iron and vitamin supplement for anemia",
    "ingredients": "Ferrous fumarate + folic acid + Vitamin B12",
    "sideEffects": "Constipation, nausea",
    "warnings": "Avoid taking with milk",
    "interactions": "Antacids, calcium, tetracycline",
    "age": "Safe for adults",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Doctor-recommended for iron"],
    "alternatives": ["Dexorange", "Feronia-XT"],
    "brands": ["Livogen"]
  },
  "pan_d": {
    "name": "Pan-D",
    "purpose": "Acidity, GERD, gas, bloating",
    "ingredients": "Pantoprazole 40mg + Domperidone 30mg",
    "sideEffects": "Headache, dry mouth, diarrhea",
    "warnings": "Do not crush; take before food",
    "interactions": "Antacids, ketoconazole, digoxin",
    "age": "Adults only",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Widely used for acid reflux"],
    "alternatives": ["Pantocid D", "Razo D"],
    "brands": ["Pan-D"]
  },
  "pantocid_d": {
    "name": "Pantocid D",
    "purpose": "Acid reflux, bloating, nausea",
    "ingredients": "Pantoprazole + Domperidone",
    "sideEffects": "Loose stools, dizziness",
    "warnings": "Avoid crushing the tablet",
    "interactions": "Warfarin, ketoconazole",
    "age": "Adults",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Common gastro remedy"],
    "alternatives": ["Pan-D", "Razo D"],
    "brands": ["Pantocid D"]
  },
  "razo_d": {
    "name": "Razo D",
    "purpose": "Acidity, heartburn, nausea",
    "ingredients": "Rabeprazole + Domperidone",
    "sideEffects": "Headache, diarrhea",
    "warnings": "Take on empty stomach",
    "interactions": "Digoxin, antifungals",
    "age": "Adults",
    "pregnancy": "Avoid unless prescribed",
    "diabetes": "Safe",
    "trust": ["Effective proton-pump inhibitor combo"],
    "alternatives": ["Pan-D", "Pantocid D"],
    "brands": ["Razo D"]
  },
  "benadon": {
    "name": "Benadon",
    "purpose": "Vitamin B6 deficiency, nausea in pregnancy",
    "ingredients": "Pyridoxine 40mg",
    "sideEffects": "Very rare: nerve tingling with overdose",
    "warnings": "Do not exceed dosage",
    "interactions": "Levodopa (without carbidopa)",
    "age": "Adults and teens",
    "pregnancy": "Safe and commonly used",
    "diabetes": "Safe",
    "trust": ["Pregnancy-safe vitamin"],
    "alternatives": ["Pyridox", "Vitamin B6"],
    "brands": ["Benadon"]
  },

  "a_to_z_ns": {
    "name": "A to Z NS",
    "purpose": "Multivitamin with minerals for immunity",
    "ingredients": "Vitamin A to Zinc, with selenium",
    "sideEffects": "Nausea, metallic taste (rare)",
    "warnings": "Avoid mega-dosing",
    "interactions": "Tetracyclines, levodopa",
    "age": "Adults",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe (sugar-free)",
    "trust": ["Balanced micronutrient profile"],
    "alternatives": ["Zincovit", "Supradyn"],
    "brands": ["A to Z"]
  },
  "supradyn": {
    "name": "Supradyn",
    "purpose": "Energy booster and antioxidant support",
    "ingredients": "Multivitamins with minerals and coenzyme Q10",
    "sideEffects": "Yellow urine, occasional headache",
    "warnings": "Do not use with other supplements",
    "interactions": "Minimal",
    "age": "Adults only",
    "pregnancy": "Use under medical advice",
    "diabetes": "Safe",
    "trust": ["Trusted vitality tablet"],
    "alternatives": ["Zincovit", "Revital H"],
    "brands": ["Supradyn"]
  },
  "revital_h_men": {
    "name": "Revital H",
    "purpose": "Daily health supplement for men",
    "ingredients": "Ginseng, vitamins, minerals",
    "sideEffects": "Insomnia, restlessness (rare)",
    "warnings": "Avoid if hypertensive",
    "interactions": "Caffeine, anticoagulants",
    "age": "Adults (18+)",
    "pregnancy": "Not for use",
    "diabetes": "Safe with caution",
    "trust": ["Popular OTC health tonic"],
    "alternatives": ["Supradyn", "Zincovit"],
    "brands": ["Revital H"]
  },
  "revital_h_woman": {
    "name": "Revital H Woman",
    "purpose": "Daily health supplement for women",
    "ingredients": "Vitamins, iron, ginseng, calcium",
    "sideEffects": "Mild GI upset",
    "warnings": "Avoid with other multivitamins",
    "interactions": "Antacids, thyroid meds",
    "age": "Women above 18",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Female-specific formula"],
    "alternatives": ["Supradyn", "Zincovit"],
    "brands": ["Revital H Woman"]
  },
  "rablet_d": {
    "name": "Rablet D",
    "purpose": "Acid reflux, nausea, heartburn",
    "ingredients": "Rabeprazole 20mg + Domperidone 30mg",
    "sideEffects": "Dry mouth, dizziness, diarrhea",
    "warnings": "Take before meals, avoid crushing",
    "interactions": "Antifungals, warfarin, digoxin",
    "age": "Adults only",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Prescribed for GERD & acidity"],
    "alternatives": ["Pan-D", "Razo D"],
    "brands": ["Rablet D"]
  },
  
  "caripill": {
    "name": "Caripill",
    "purpose": "Increases platelet count (e.g. dengue recovery)",
    "ingredients": "Carica papaya leaf extract",
    "sideEffects": "GI upset (rare)",
    "warnings": "Not a cure for dengue, only supportive",
    "interactions": "None known",
    "age": "Teens and adults",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Natural supportive therapy"],
    "alternatives": ["Platexid", "Papaya syrup"],
    "brands": ["Caripill"]
  },
  "becadexamin": {
    "name": "Becadexamin",
    "purpose": "Daily multivitamin & mineral supplement",
    "ingredients": "Vitamins A, B-complex, C, D, E, minerals",
    "sideEffects": "Yellow urine, nausea (rare)",
    "warnings": "Avoid with other supplements",
    "interactions": "Tetracyclines, diuretics",
    "age": "Adults",
    "pregnancy": "Consult doctor",
    "diabetes": "Use sugar-free version",
    "trust": ["Oldest Indian multivitamin"],
    "alternatives": ["Supradyn", "Zincovit"],
    "brands": ["Becadexamin"]
  },
  "rinifol": {
    "name": "Rinifol",
    "purpose": "Diarrhea with vitamin deficiency",
    "ingredients": "Ofloxacin, Ornidazole, Lactobacillus, vitamins",
    "sideEffects": "Nausea, dizziness, GI upset",
    "warnings": "Complete the full course",
    "interactions": "Alcohol, antacids, warfarin",
    "age": "Adults only",
    "pregnancy": "Avoid unless prescribed",
    "diabetes": "Safe",
    "trust": ["Trusted combo for loose motions"],
    "alternatives": ["Norflox TZ", "Metrogyl"],
    "brands": ["Rinifol"]
  },
  "okacet": {
    "name": "Okacet",
    "purpose": "Allergy, sneezing, cold",
    "ingredients": "Cetirizine 10mg",
    "sideEffects": "Drowsiness, dry mouth",
    "warnings": "Avoid alcohol, driving",
    "interactions": "Sedatives, alcohol",
    "age": "Above 6 years",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Widely available anti-allergy"],
    "alternatives": ["Cetzine", "Zyrtec"],
    "brands": ["Okacet"]
  },
  "nexpro_rd": {
    "name": "Nexpro RD",
    "purpose": "GERD, acidity, nausea",
    "ingredients": "Esomeprazole + Domperidone",
    "sideEffects": "Flatulence, dizziness",
    "warnings": "Do not chew; take 30 min before food",
    "interactions": "Warfarin, ketoconazole",
    "age": "Adults",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Effective reflux relief"],
    "alternatives": ["Pan-D", "Razo D"],
    "brands": ["Nexpro RD"]
  },
  "unienzyme": {
    "name": "Unienzyme",
    "purpose": "Indigestion, gas, bloating",
    "ingredients": "Fungal diastase, papain, activated charcoal",
    "sideEffects": "Mild constipation (rare)",
    "warnings": "Avoid overdose",
    "interactions": "None significant",
    "age": "12+ years",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Enzyme-based digestion aid"],
    "alternatives": ["Aristozyme", "Gas-O-Fast"],
    "brands": ["Unienzyme"]
  },
  "aristozyme": {
    "name": "Aristozyme",
    "purpose": "Indigestion, poor appetite",
    "ingredients": "Fungal diastase + Pepsin",
    "sideEffects": "Rare: nausea or bloating",
    "warnings": "Consult for long-term use",
    "interactions": "Minimal",
    "age": "Children and adults",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Pediatric & adult enzyme syrup"],
    "alternatives": ["Unienzyme", "Gas-O-Fast"],
    "brands": ["Aristozyme"]
  },
  "grilinctus": {
    "name": "Grilinctus",
    "purpose": "Cough suppressant for dry cough",
    "ingredients": "Dextromethorphan, Chlorpheniramine, Guaiphenesin",
    "sideEffects": "Drowsiness, dry mouth",
    "warnings": "Avoid driving or alcohol",
    "interactions": "MAO inhibitors, sedatives",
    "age": "Adults and teens",
    "pregnancy": "Avoid unless prescribed",
    "diabetes": "Check sugar-free version",
    "trust": ["Popular dry cough syrup"],
    "alternatives": ["Chericof", "Ascoril D"],
    "brands": ["Grilinctus"]
  },
  
  "zedex_c": {
    "name": "Zedex C",
    "purpose": "Cough with throat irritation",
    "ingredients": "Dextromethorphan, Chlorpheniramine, Phenylephrine",
    "sideEffects": "Sleepiness, dry mouth",
    "warnings": "Avoid with sedatives/alcohol",
    "interactions": "MAOIs, antidepressants",
    "age": "Above 6 years",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe (sugar-free available)",
    "trust": ["OTC cold and cough remedy"],
    "alternatives": ["Grilinctus", "Ascoril D"],
    "brands": ["Zedex C"]
  },
  "koflet": {
    "name": "Koflet",
    "purpose": "Mild cough relief (herbal)",
    "ingredients": "Honey, tulsi, licorice, clove, turmeric",
    "sideEffects": "Very rare: allergy",
    "warnings": "Avoid in diabetic children unless sugar-free",
    "interactions": "Minimal",
    "age": "Children and adults",
    "pregnancy": "Safe",
    "diabetes": "Check sugar content",
    "trust": ["Ayurvedic mild cough remedy"],
    "alternatives": ["Honitus", "Tulsicof"],
    "brands": ["Koflet"]
  },
  "honitus": {
    "name": "Honitus",
    "purpose": "Cough and throat soothing (herbal)",
    "ingredients": "Honey, tulsi, mulethi, banapsha",
    "sideEffects": "Rare: allergy to herbs",
    "warnings": "Do not overdose",
    "interactions": "Minimal",
    "age": "2+ years",
    "pregnancy": "Safe",
    "diabetes": "Check sugar-free version",
    "trust": ["Trusted Ayurvedic brand"],
    "alternatives": ["Koflet", "Tulsicof"],
    "brands": ["Honitus"]
  },
  "coughrid": {
    "name": "Coughrid",
    "purpose": "Wet cough and congestion",
    "ingredients": "Ambroxol, Guaiphenesin, Terbutaline",
    "sideEffects": "Bloating, dry mouth",
    "warnings": "Avoid if hypertensive",
    "interactions": "Beta-blockers, CNS stimulants",
    "age": "Adults and children",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Effective syrup for phlegm"],
    "alternatives": ["Ambrodil LS", "Ascoril LS"],
    "brands": ["Coughrid"]
  },
  "dolo_d": {
    "name": "Dolo D",
    "purpose": "Cold, flu, mild body pain",
    "ingredients": "Paracetamol + Phenylephrine + Chlorpheniramine",
    "sideEffects": "Sleepiness, dry mouth, dizziness",
    "warnings": "Avoid driving, alcohol",
    "interactions": "MAO inhibitors, sedatives",
    "age": "Adults and teens",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Dolo brand flu relief"],
    "alternatives": ["Sinarest", "Decoff"],
    "brands": ["Dolo D"]
  },
  "zyrcold": {
    "name": "ZyrCold",
    "purpose": "Cold, congestion, sneezing",
    "ingredients": "Paracetamol, Phenylephrine, Cetirizine",
    "sideEffects": "Drowsiness, dry mouth",
    "warnings": "Avoid with alcohol or sedatives",
    "interactions": "MAO inhibitors, other antihistamines",
    "age": "12+ years",
    "pregnancy": "Consult doctor",
    "diabetes": "Safe",
    "trust": ["Common flu combination"],
    "alternatives": ["Sinarest", "D Cold Total"],
    "brands": ["ZyrCold"]
  },
  "nasivion_adult": {
    "name": "Nasivion Adult",
    "purpose": "Nasal decongestion (oral capsules also available)",
    "ingredients": "Oxymetazoline hydrochloride (tablet/capsule variant)",
    "sideEffects": "Nasal dryness, headache",
    "warnings": "Do not use continuously >5 days",
    "interactions": "MAO inhibitors",
    "age": "Above 12 years",
    "pregnancy": "Use with caution",
    "diabetes": "Safe",
    "trust": ["Backed by Bayer"],
    "alternatives": ["Otrivin", "Sinarest"],
    "brands": ["Nasivion"]
  },
  "strepsils_lozenges": {
    "name": "Strepsils Lozenges",
    "purpose": "Sore throat, throat pain relief",
    "ingredients": "2,4-Dichlorobenzyl alcohol, Amylmetacresol",
    "sideEffects": "Mouth irritation, rare allergy",
    "warnings": "Do not swallow whole",
    "interactions": "None significant",
    "age": "Above 6 years",
    "pregnancy": "Safe",
    "diabetes": "Use sugar-free variant",
    "trust": ["Widely used OTC throat relief"],
    "alternatives": ["Vicks Lozenges", "Halls"],
    "brands": ["Strepsils"]
  },
  "vicks_action_500": {
    "name": "Vicks Action 500",
    "purpose": "Cold, headache, sinus relief",
    "ingredients": "Paracetamol, Phenylephrine, Caffeine",
    "sideEffects": "Irritability, insomnia (from caffeine)",
    "warnings": "Avoid at night due to caffeine",
    "interactions": "Sedatives, MAO inhibitors",
    "age": "Adults",
    "pregnancy": "Avoid unless prescribed",
    "diabetes": "Safe",
    "trust": ["Common cold pill in India"],
    "alternatives": ["Sinarest", "D Cold Total"],
    "brands": ["Vicks Action 500"]
  },
  "calpol_650": {
    "name": "Calpol 650",
    "purpose": "Fever, headache, body pain",
    "ingredients": "Paracetamol 650mg",
    "sideEffects": "Liver toxicity if overdosed",
    "warnings": "Do not exceed 4 tablets/day",
    "interactions": "Alcohol, liver-affecting drugs",
    "age": "Adults",
    "pregnancy": "Safe in standard doses",
    "diabetes": "Safe",
    "trust": ["Popular fever medication"],
    "alternatives": ["Dolo 650", "Crocin 650"],
    "brands": ["Calpol"]
  },
  "crocin_advance": {
    "name": "Crocin Advance",
    "purpose": "Fever, pain relief",
    "ingredients": "Paracetamol 500mg",
    "sideEffects": "Rare rash, liver risk on overdose",
    "warnings": "Avoid exceeding dose",
    "interactions": "Warfarin, alcohol",
    "age": "Safe for all (dose as per age)",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Widely available OTC tablet"],
    "alternatives": ["Dolo 650", "Calpol"],
    "brands": ["Crocin"]
  },
  "medomol": {
    "name": "Medomol",
    "purpose": "Fever, pain relief",
    "ingredients": "Paracetamol 500mg",
    "sideEffects": "Liver damage on overdose",
    "warnings": "Keep 4-6 hour gap between doses",
    "interactions": "Alcohol",
    "age": "Safe above 5 years",
    "pregnancy": "Safe",
    "diabetes": "Safe",
    "trust": ["Generic alternative"],
    "alternatives": ["Calpol", "Crocin"],
    "brands": ["Medomol"]
  },
  "flexon": {
    "name": "Flexon",
    "purpose": "Fever, pain, inflammation",
    "ingredients": "Paracetamol + Ibuprofen",
    "sideEffects": "Acidity, nausea, dizziness",
    "warnings": "Take after meals to reduce acidity",
    "interactions": "Blood thinners, antihypertensives",
    "age": "Adults",
    "pregnancy": "Avoid in 3rd trimester",
    "diabetes": "Safe",
    "trust": ["Combination painkiller"],
    "alternatives": ["Combiflam", "Ibugesic Plus"],
    "brands": ["Flexon"]
  },
  "combiflam": {
    "name": "Combiflam",
    "purpose": "Headache, muscle pain, fever",
    "ingredients": "Ibuprofen 400mg + Paracetamol 325mg",
    "sideEffects": "Stomach pain, nausea",
    "warnings": "Avoid on empty stomach",
    "interactions": "Alcohol, blood thinners",
    "age": "Above 12 years",
    "pregnancy": "Avoid",
    "diabetes": "Safe",
    "trust": ["Top-selling painkiller combo"],
    "alternatives": ["Flexon", "Ibugesic Plus"],
    "brands": ["Combiflam"]
  },
  "ibugesic_plus": {
    "name": "Ibugesic Plus",
    "purpose": "Fever, pain, toothache",
    "ingredients": "Ibuprofen + Paracetamol",
    "sideEffects": "Acidity, dizziness",
    "warnings": "Take after food",
    "interactions": "Warfarin, steroids",
    "age": "Children and adults (age-specific dosing)",
    "pregnancy": "Avoid",
    "diabetes": "Safe",
    "trust": ["Popular pediatric & adult painkiller"],
    "alternatives": ["Combiflam", "Flexon"],
    "brands": ["Ibugesic Plus"]
  },
  "vitamin_d3_60000": {
    "name": "Vitamin D3 60000 IU",
    "purpose": "Vitamin D deficiency treatment and bone health support",
    "ingredients": "Cholecalciferol (Vitamin D3) 60000 IU",
    "sideEffects": "Nausea, vomiting, weakness, kidney problems (if overdosed)",
    "warnings": "Do not exceed recommended dose; monitor calcium levels during treatment",
    "interactions": "Thiazide diuretics, digitalis, calcium supplements",
    "age": "Adults and adolescents above 12 years",
    "pregnancy": "Safe in recommended doses, consult doctor",
    "diabetes": "Safe, may help improve insulin sensitivity",
    "trust": ["Prescription vitamin supplement", "Doctor recommended"],
    "alternatives": ["Calcirol", "Arachitol", "Uprise D3"],
    "brands": ["D-Rise", "Uprise", "Calcirol"]
  },
  "d_rise": {
    "name": "D-Rise 60K",
    "purpose": "High-dose Vitamin D3 for severe deficiency",
    "ingredients": "Cholecalciferol 60000 IU",
    "sideEffects": "Hypercalcemia, nausea, fatigue, kidney stones (rare)",
    "warnings": "Take only as prescribed; usually weekly or monthly dosing",
    "interactions": "Calcium supplements, heart medications, water pills",
    "age": "Adults only, children require different dosing",
    "pregnancy": "Generally safe, monitor levels",
    "diabetes": "Safe and beneficial",
    "trust": ["USV Pharma", "Widely prescribed"],
    "alternatives": ["Uprise D3", "Calcirol sachets", "Arachitol"],
    "brands": ["D-Rise"]
  }

}

module.exports = data;